version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: fwa-postgres
    environment:
      POSTGRES_DB: fwa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: subscription-backend
    container_name: fwa-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata: