services:
  postgres:
    image: postgres:16
    container_name: fwa-postgres
    environment:
      POSTGRES_DB: fwa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: hamoudaakriche/subscription-backend:latest
    container_name: fwa-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    image: hamoudaakriche/subscription-frontend:latest
    container_name: fwa-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  pgdata: