apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "adminfwa"          # Remplace par ton utilisateur Azure
  POSTGRES_PASSWORD: "Juniorronaldo7!" # Remplace par ton mot de passe Azure
  POSTGRES_DB: "fwa_db"              # Le nom de ta base de données sur Azure