# 1. Service pour la VM Locale (Cloud Privé)
apiVersion: v1
kind: Service
metadata:
  name: cloud-prive-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30080

---
# 2. Endpoints avec ton IP (197.3.213.147)
apiVersion: v1
kind: Endpoints
metadata:
  name: cloud-prive-service
  namespace: default
subsets:
  - addresses:
      - ip: 197.3.213.147
    ports:
      - port: 30080

---
# 3. ServersTransport pour accélérer l'abandon si la VM privée ne répond pas
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pfe-fast-timeout
  namespace: default
spec:
  forwardingTimeouts:
    dialTimeout: 1s      # Si la VM ne répond pas au ping TCP en 1s, elle est considérée HS
    responseHeaderTimeout: 2s  # Si le backend met plus de 2s à répondre, on bascule

---
# 4. L'IngressRoute Principal
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-principal
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fwasubscription.myvnc.com`)
      kind: Rule
      services:
        - name: pfe-failover
          kind: TraefikService

---
# 5. Le TraefikService de failover
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: pfe-failover
  namespace: default
spec:
  failover:
    service:
      name: cloud-prive-service
      kind: Service
      port: 80
      serversTransport: pfe-fast-timeout
    fallback:
      name: fwa-subscription-ui
      kind: Service
      port: 80
    errors:
      status:
        - "500-504"
        - "429"