# 1. Le Service interne dans AKS (Pointe vers les Endpoints de ta VM locale)
apiVersion: v1
kind: Service
metadata:
  name: cloud-prive-service
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80         # Le port virtuel dans AKS
      targetPort: 30080 # Le port réel de ta VM locale

---
# 2. Les Endpoints (Lien vers l'IP fixe de ta VM)
apiVersion: v1
kind: Endpoints
metadata:
  name: cloud-prive-service
  namespace: default
subsets:
  - addresses:
      - ip: 41.62.239.89 # L'IP fixe de ta VM locale
    ports:
      - port: 30080

---
# 3. L'IngressRoute Principal (Il pointe vers le répartiteur Traefik)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-principal
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`fwasubscription.myvnc.com`)
      kind: Rule
      services:
        # On ne pointe plus directement vers les services, mais vers le gestionnaire de répartition ci-dessous
        - name: pfe-loadbalancer-service
          kind: TraefikService

---
# 4. Le Répartiteur de charge Traefik (Gestion du Load Balancing + Sticky Sessions)
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: pfe-loadbalancer-service
  namespace: default
spec:
  # C'est cette option qui va empêcher le bug 403 en te laissant sur le cloud où tu t'es connecté !
  sticky:
    cookie:
      name: pfe_sticky_session
  weighted:
    services:
      - name: cloud-prive-service        # Cloud Privé (VM)
        port: 80
        weight: 1                        # Poids équivalent (50% de la charge)
      - name: fwa-subscription-ui        # Cloud Public (Azure AKS)
        port: 80
        weight: 1                        # Poids équivalent (50% de la charge)